using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraBars;
using MySql.Data.MySqlClient;

namespace 课程设计
{
    public partial class manager : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public manager()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
        }

        //学生的
        private void barButtonItem7_ItemClick(object sender, ItemClickEventArgs e)
        {
            string Sno = StuView.GetRowCellValue(StuView.FocusedRowHandle, "Sno").ToString();
            string Sname = StuView.GetRowCellValue(StuView.FocusedRowHandle, "Sname").ToString();
            string Ssex = StuView.GetRowCellValue(StuView.FocusedRowHandle, "Ssex").ToString();
            string Sage = StuView.GetRowCellValue(StuView.FocusedRowHandle, "Sage").ToString();
            string Smajor = StuView.GetRowCellValue(StuView.FocusedRowHandle, "Smajor").ToString();
            ShowDetail chart = new ShowDetail("学生", Sname, Sno, Ssex, Sage, Smajor);
            if (chart.ShowDialog() == DialogResult.OK)
            {
                MessageBox.Show("修改成功");
                this.学生选课管理系统DataSet.AcceptChanges();
                this.stuTableAdapter.Fill(this.学生选课管理系统DataSet1.stu);
                StuView.RefreshData();
            }
        }

        private void barButtonItem8_ItemClick(object sender, ItemClickEventArgs e)
        {
            Add_M add = new Add_M("学生");
            if (add.ShowDialog() == DialogResult.OK)
            {
                MessageBox.Show("添加成功！");
                this.学生选课管理系统DataSet.AcceptChanges();
                this.stuTableAdapter.Fill(this.学生选课管理系统DataSet.stu);
                StuView.RefreshData();
            }
        }

        private void barButtonItem9_ItemClick(object sender, ItemClickEventArgs e)
        {
            List<int> selectedRows;//筛选选中的行，非数据行的不要
            string connString = "server=localhost;user id=root; password=usb2.030mbs;database=学生选课管理系统;Charset=utf8;";
            MySqlConnection connection = new MySqlConnection(connString);
            connection.Open();
            selectedRows = StuView.GetSelectedRows().Where((t)=> t>=0).ToList();
            foreach (int i in selectedRows)
            {
                string sql = "DELETE FROM stu where Sno=@Sno";
                String Sno = this.StuView.GetRowCellValue(i,"Sno").ToString();
                MySqlCommand command = new MySqlCommand(sql, connection);
                command.Parameters.AddWithValue("Sno", Sno);
                command.ExecuteNonQuery();
                command = null;
                StuView.GetDataRow(i).Delete();
            }
            MessageBox.Show("删除成功");
            connection.Close();
        }

        private void barButtonItem10_ItemClick(object sender, ItemClickEventArgs e)
        {
            ManagridControl.DataSource = null;
            ManagridControl.MainView = TeachView; // a GridView from the Views repository (configured at design time)
            ManagridControl.DataSource = teacherBindingSource;  // a data source for gridView2
        }

        private void barButtonItem18_ItemClick(object sender, ItemClickEventArgs e)
        {

        }

        private void barButtonItem19_ItemClick(object sender, ItemClickEventArgs e)
        {
            login log = new login();
            log.Show();
            this.Close();
        }

        private void manager_Load(object sender, EventArgs e)
        {
            // TODO: 这行代码将数据加载到表“学生选课管理系统DataSet.classroom”中。您可以根据需要移动或删除它。
            this.classroomTableAdapter.Fill(this.学生选课管理系统DataSet.classroom);
            // TODO: 这行代码将数据加载到表“学生选课管理系统DataSet.teacher”中。您可以根据需要移动或删除它。
            this.teacherTableAdapter.Fill(this.学生选课管理系统DataSet.teacher);
            // TODO: 这行代码将数据加载到表“学生选课管理系统DataSet.stu”中。您可以根据需要移动或删除它。
            this.stuTableAdapter.Fill(this.学生选课管理系统DataSet.stu);
            // TODO: 这行代码将数据加载到表“学生选课管理系统DataSet.stu”中。您可以根据需要移动或删除它。


        }

        private void dataGridView1_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {

        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void stuBindingNavigatorSaveItem_Click(object sender, EventArgs e)
        {
            this.Validate();

        }

        private void barButtonItem6_ItemClick(object sender, ItemClickEventArgs e)
        {
            ManagridControl.DataSource = null;
            ManagridControl.MainView = StuView; // a GridView from the Views repository (configured at design time)
            ManagridControl.DataSource = stuBindingSource;  // a data source for gridView2
        }

        private void barButtonItem14_ItemClick(object sender, ItemClickEventArgs e)
        {
            ManagridControl.DataSource = null;
            ManagridControl.MainView = RoomView; // a GridView from the Views repository (configured at design time)
            ManagridControl.DataSource = classroomBindingSource;  // a data source for gridView2
        }

        private void barButtonItem13_ItemClick(object sender, ItemClickEventArgs e)
        {
            List<int> selectedRows;//筛选选中的行，非数据行的不要
            string connString = "server=localhost;user id=root; password=usb2.030mbs;database=学生选课管理系统;Charset=utf8;";
            MySqlConnection connection = new MySqlConnection(connString);
            connection.Open();
            selectedRows = TeachView.GetSelectedRows().Where((t) => t >= 0).ToList();
            foreach (int i in selectedRows)
            {
                string sql = "DELETE FROM teacher where Tno=@Tno";
                String Tno = this.TeachView.GetRowCellValue(i, "Tno").ToString();
                MySqlCommand command = new MySqlCommand(sql, connection);
                command.Parameters.AddWithValue("Tno", Tno);
                command.ExecuteNonQuery();
                command = null;
                TeachView.GetDataRow(i).Delete();
            }
            MessageBox.Show("删除成功");
            connection.Close();
        }

        private void barButtonItem17_ItemClick(object sender, ItemClickEventArgs e)
        {
            List<int> selectedRows;//筛选选中的行，非数据行的不要
            string connString = "server=localhost;user id=root; password=usb2.030mbs;database=学生选课管理系统;Charset=utf8;";
            MySqlConnection connection = new MySqlConnection(connString);
            connection.Open();
            selectedRows = RoomView.GetSelectedRows().Where((t) => t >= 0).ToList();
            foreach (int i in selectedRows)
            {
                string sql = "DELETE FROM classroom where Rid=@Rid";
                String Rid = this.RoomView.GetRowCellValue(i, "Rid").ToString();
                MySqlCommand command = new MySqlCommand(sql, connection);
                command.Parameters.AddWithValue("Rid", Rid);
                command.ExecuteNonQuery();
                command = null;
                RoomView.GetDataRow(i).Delete();
            }
            MessageBox.Show("删除成功");
            connection.Close();
        }

        private void label1_Click(object sender, EventArgs e)
        {

        }

        private void label5_Click(object sender, EventArgs e)
        {

        }

        private void textBox4_TextChanged(object sender, EventArgs e)
        {

        }

        private void textBox5_TextChanged(object sender, EventArgs e)
        {

        }

        private void ManagridControl_Click(object sender, EventArgs e)
        {

        }
        private void StuView_MouseDown(object sender, MouseEventArgs e)
        {
            DevExpress.XtraGrid.Views.Grid.ViewInfo.GridHitInfo hInfo = StuView.CalcHitInfo(new Point(e.X, e.Y));
            if (e.Button == MouseButtons.Left && e.Clicks == 2)
            {
                // 判断光标是否在行范围内
                if (hInfo.InRow)
                {
                    // do something
                    string Sno = StuView.GetRowCellValue(StuView.FocusedRowHandle, "Sno").ToString();
                    string Sname = StuView.GetRowCellValue(StuView.FocusedRowHandle, "Sname").ToString();
                    string Ssex = StuView.GetRowCellValue(StuView.FocusedRowHandle, "Ssex").ToString();
                    string Sage = StuView.GetRowCellValue(StuView.FocusedRowHandle, "Sage").ToString();
                    string Smajor = StuView.GetRowCellValue(StuView.FocusedRowHandle, "Smajor").ToString();
                    ShowDetail chart = new ShowDetail("学生", Sname, Sno, Ssex, Sage, Smajor);
                    if (chart.ShowDialog() == DialogResult.OK) {
                        MessageBox.Show("修改成功");
                        this.学生选课管理系统DataSet.AcceptChanges();
                        this.stuTableAdapter.Fill(this.学生选课管理系统DataSet.stu);
                        StuView.RefreshData();
                    }
                }
            }
        }

        private void TeachView_MouseDown(object sender, MouseEventArgs e)
        {
            DevExpress.XtraGrid.Views.Grid.ViewInfo.GridHitInfo hInfo = TeachView.CalcHitInfo(new Point(e.X, e.Y));
            if (e.Button == MouseButtons.Left && e.Clicks == 2)
            {
                // 判断光标是否在行范围内
                if (hInfo.InRow)
                {
                    // do something
                    string Tno = TeachView.GetRowCellValue(TeachView.FocusedRowHandle, "Tno").ToString();
                    string Tname = TeachView.GetRowCellValue(TeachView.FocusedRowHandle, "Tname").ToString();
                    string Tsex = TeachView.GetRowCellValue(TeachView.FocusedRowHandle, "Tsex").ToString();
                    string Tage = TeachView.GetRowCellValue(TeachView.FocusedRowHandle, "Tage").ToString();
                    string Tmajor = TeachView.GetRowCellValue(TeachView.FocusedRowHandle, "Tmajor").ToString();
                    ShowDetail chart = new ShowDetail("教师", Tname, Tno, Tsex, Tage, Tmajor);
                    if (chart.ShowDialog() == DialogResult.OK)
                    {
                        MessageBox.Show("修改成功");
                        this.学生选课管理系统DataSet.AcceptChanges();
                        this.teacherTableAdapter.Fill(this.学生选课管理系统DataSet.teacher);
                        TeachView.RefreshData();
                    }
                }
            }
        }

        private void barButtonItem12_ItemClick(object sender, ItemClickEventArgs e)
        {
            Add_M add = new Add_M("教师");
            if (add.ShowDialog() == DialogResult.OK)
            {
                MessageBox.Show("添加成功！");
                this.学生选课管理系统DataSet.AcceptChanges();
                this.teacherTableAdapter.Fill(this.学生选课管理系统DataSet.teacher);
                TeachView.RefreshData();
            }
        }

        private void barButtonItem16_ItemClick(object sender, ItemClickEventArgs e)
        {
            Add_M add = new Add_M("教室");
            if (add.ShowDialog() == DialogResult.OK) {
                MessageBox.Show("添加成功！");
                this.学生选课管理系统DataSet.AcceptChanges();
                this.classroomTableAdapter.Fill(this.学生选课管理系统DataSet.classroom);
                RoomView.RefreshData();
            }
        }

        private void barButtonItem5_ItemClick(object sender, ItemClickEventArgs e)
        {
            this.学生选课管理系统DataSet.AcceptChanges();
            this.classroomTableAdapter.Fill(this.学生选课管理系统DataSet.classroom);
            this.teacherTableAdapter.Fill(this.学生选课管理系统DataSet.teacher);
            this.stuTableAdapter.Fill(this.学生选课管理系统DataSet.stu);
        }

        //教师的
        private void barButtonItem20_ItemClick(object sender, ItemClickEventArgs e)
        {
            string Tno = TeachView.GetRowCellValue(TeachView.FocusedRowHandle, "Tno").ToString();
            string Tname = TeachView.GetRowCellValue(TeachView.FocusedRowHandle, "Tname").ToString();
            string Tsex = TeachView.GetRowCellValue(TeachView.FocusedRowHandle, "Tsex").ToString();
            string Tage = TeachView.GetRowCellValue(TeachView.FocusedRowHandle, "Tage").ToString();
            string Tmajor = TeachView.GetRowCellValue(TeachView.FocusedRowHandle, "Tmajor").ToString();
            ShowDetail chart = new ShowDetail("教师", Tname, Tno, Tsex, Tage, Tmajor);
            if (chart.ShowDialog() == DialogResult.OK)
            {
                MessageBox.Show("修改成功");
                this.学生选课管理系统DataSet.AcceptChanges();
                this.teacherTableAdapter.Fill(this.学生选课管理系统DataSet.teacher);
                TeachView.RefreshData();
            }
        }
    }
}